name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
jobs:
  mac:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dotfiles
        run: |
          chmod +x bin/install.sh
          bin/install.sh install
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dotfiles
        run: |
          chmod +x bin/install.sh
          bin/install.sh install
