name: CI
on: [push]
jobs:
  mac:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          mkdir -p $HOME/Library/Application\ Support/Code/User
          touch $HOME/Library/Application\ Support/Code/User/settings.json
      - name: Install dotfiles
        run: |
          chmod +x bin/install.sh
          bin/install.sh install
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          mkdir -p $HOME/Library/Application\ Support/Code/User
          touch $HOME/Library/Application\ Support/Code/User/settings.json
      - name: Install dotfiles
        run: |
          chmod +x bin/install.sh
          bin/install.sh install
