name: CI
on: [push]
jobs:
  mac:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          brew update
          brew install git
          mkdir $HOME/Library/Application\ Support/Code/User
          touch $HOME/Library/Application\ Support/Code/User/settings.json
      - name: Install dotfiles
        run: bin/install.sh install
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          mkdir $HOME/Library/Application\ Support/Code/User
          touch $HOME/Library/Application\ Support/Code/User/settings.json
      - name: Install dotfiles
        run: bin/install.sh install
